version: "2"

services:
  node:
    build: .docker/node/
    env_file:
      - ./.docker/common.env
      - ./.env
    volumes:
      - "./src:/srv/htdocs/"
    ports:
      - "${PORT}:8080"
    command: npm start
